### ISSUE TITLE
Failed to load package named 'devdocs' SyntaxError: Unexpected end of input

### ISSUE THREAD

**Issue by despairblue** [masnun/atom-devdocs#2]
Happens when starting atom or reloading the view:

```
Failed to load package named 'devdocs' SyntaxError: Unexpected end of input
  at Object.parse (native)
  at parseObject (/usr/share/atom/resources/app/node_modules/season/lib/cson.js:149:19)
  at parseContentsSync (/usr/share/atom/resources/app/node_modules/season/lib/cson.js:155:14)
  at Object.module.exports.readFileSync (/usr/share/atom/resources/app/node_modules/season/lib/cson.js:220:14)
  at /usr/share/atom/resources/app/src/package.js:239:34
  at Array.map (native)
  at Package.module.exports.Package.loadKeymaps (/usr/share/atom/resources/app/src/package.js:238:51)
  at /usr/share/atom/resources/app/src/package.js:113:19
  at Package.module.exports.Package.measure (/usr/share/atom/resources/app/src/package.js:95:15)
  at Package.module.exports.Package.load (/usr/share/atom/resources/app/src/package.js:109:12)
  at PackageManager.module.exports.PackageManager.loadPackage (/usr/share/atom/resources/app/src/package-manager.js:217:16)
  at PackageManager.module.exports.PackageManager.loadPackages (/usr/share/atom/resources/app/src/package-manager.js:198:14)
  at Atom.module.exports.Atom.startEditorWindow (/usr/share/atom/resources/app/src/atom.js:365:21)
  at Object.<anonymous> (/usr/share/atom/resources/app/src/window-bootstrap.js:14:8)
  at Object.<anonymous> (/usr/share/atom/resources/app/src/window-bootstrap.js:20:4)
  at Module._compile (module.js:455:26)
  at Object.Module._extensions..js (module.js:473:10)
  at Module.load (/usr/share/atom/resources/app/node_modules/coffee-script/lib/coffee-script/register.js:45:36)
  at Function.Module._load (module.js:311:12)
  at Module.require (module.js:363:17)
  at require (module.js:379:177)
  at window.onload (file:///usr/share/atom/resources/app/static/index.js:20:5)
 /usr/share/atom/resources/app/src/package.js:122
```

Package works as expected nevertheless. 
## Versions
- **Atom:** 0.120.0
- **devdocs:** 0.2.0
- **platform:** Arch Linux

**Comment by masnun** [comment]
Does this still happen in the latest version of Atom?
