### ISSUE TITLE
Failed to activate the devdocs package

### ISSUE THREAD

**Issue by n370** [masnun/atom-devdocs#5]
[Enter steps to reproduce below:]

1. Open atom.

**Atom Version**: 0.200.0 :warning: **in 1.0 API Preview Mode** :warning:
**System**: Mac OS X 10.10.3
**Thrown From**: [devdocs](https://github.com/masnun/atom-devdocs) package, v0.2.0

### Stack Trace

Failed to activate the devdocs package

```
At Cannot read property 'command' of undefined

TypeError: Cannot read property 'command' of undefined
    at Object.module.exports.activate (/Users/me/.atom/packages/devdocs/lib/devdocs.js:3:27)
    at Package.module.exports.Package.activateNow (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:238:19)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/package.js:219:30
    at Package.module.exports.Package.measure (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:163:15)
    at Package.module.exports.Package.activate (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:211:14)
    at PackageManager.module.exports.PackageManager.activatePackage (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:435:21)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:419:29
    at Config.module.exports.Config.transact (/Applications/Atom.app/Contents/Resources/app.asar/src/config.js:311:16)
    at PackageManager.module.exports.PackageManager.activatePackages (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:414:19)
    at PackageManager.module.exports.PackageManager.activate (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:395:46)
    at Atom.module.exports.Atom.startEditorWindow (/Applications/Atom.app/Contents/Resources/app.asar/src/atom.js:636:21)
    at Object.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/window-bootstrap.js:12:8)
    at Object.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/window-bootstrap.js:23:4)
    at Module._compile (module.js:452:26)
    at Object.loadFile [as .js] (/Applications/Atom.app/Contents/Resources/app.asar/src/babel.js:162:21)
    at Module.load (module.js:347:32)
```

### Commands

```
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "linter-jscs",
      "jslint"
    ],
    "themes": [
      "one-dark-ui",
      "monokai"
    ]
  }
}
```

### Installed Packages

```coffee
# User
angularjs-styleguide-snippets, v0.7.0
atom-jade, v0.1.0
color-picker, v1.7.0
devdocs, v0.2.0
docblockr, v0.7.1
editorconfig, v1.0.0
emmet, v2.3.9
jsformat, v0.8.1
linter, v0.12.4
linter-jshint, v0.1.4
monokai, v0.14.0
pdf-view, v0.22.0
pretty-json, v0.3.3

# Dev
No dev packages
```

**Comment by masnun** [comment]
Hi Thanks for the report, I am not getting enough time to fix the issue. I shall try to manage some time and get back to it. Meanwhile any PRs are most welcome.
